### ISSUE TITLE
Grade First Homework

### ISSUE THREAD

**Issue by allyflores27** [allyflores27/astr-119#3]
Hey @mattkwiecien! Could you please grade my first homework?

**Comment by matt-april** [comment]
Hi @allyflores27!  In order to get full credit on your first homework, can you first complete your PR 
and then close your open issue to "Create first homework"?  Once that's done I can go ahead and open a PR to grade your first homework, which then you can close/complete.  

These details are in the first assignment as well. If you are confused about any of this, just let me know over slack or on this issue!
